version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  target-branch: master
  ignore:
  - dependency-name: ssri
    versions:
    - 6.0.2
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.3
  - dependency-name: elliptic
    versions:
    - 6.5.4
  - dependency-name: socket.io
    versions:
    - 2.4.1
