language: node_js

node_js:
  - "12"

install:
  - npm install
  
script: npm run build

notifications:
  email:
    recipients:
      - marcelloluatti@gmail.com
    on_success: always
    on_failure: always

cache:
  npm: false