language: node_js

node_js:
  - "12"

install:
  - npm install
  
script: npm run build

deploy:
  provider: surge
  project: ./public/
  domain: asutkin-travis.surge.sh
  skip_cleanup: true
  on:
    branch: master

notifications:
  email:
    - marcelloluatti@gmail.com

cache:
  npm: false